export enum Entity {
    Merchants,
    Channels,
    ChannelProfiles,
    PosIntegrations,
    MenuCategories,
    MenuItems,
    Locals,
    Employees,
    ModifierGroups,
    CustomChargeMethods,
    PrinterWorkers,
    Printers,
    PrinterMessages,
    AcquirerConfigurations,
    Transactions,
    Reviews,
    MerchantDocuments,
    ConfigurableFields,
    ConfigurableFieldAssociations,
    Settlements,
    Availabilities,
    AvailabilityMenuItemAssociations,
    AvailabilityChannelProfileAssociations,
}

export const getEntityType = (entity: Entity): string => Entity[entity];