export enum NotificationType {
    Test = 1 << 0,
    FailedCharge = 1 << 1,
    ExpiredCharge = 1 << 2,
    PosOffline = 1 << 3,
    PosSyncFailure = 1 << 4,
    PosPaymentSyncFailure = 1 << 5,
    CompletedCharge = 1 << 6,
    NewOrder = 1 << 7,
    NewReview = 1 << 8,
    NewConsumerBill = 1 << 9,
    NewConsumerInvoice = 1 << 10,
    NewPreparationRequest = 1 << 11,
    ChargeSynced = 1 << 12,
    OpenCashDrawer = 1 << 13,
    EndOfDayClosing = 1 << 14,
}