name: Build Containers to Azure

on:
  push:
    branches:
      - main

env:
  ACR_NAME: quiviregistry
  RESOURCE_GROUP: quivi-resourcegroup
  LOCATION: westeurope

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Sandbox

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name $ACR_NAME

      - name: Build Quivi.Migrator
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/quivi.migrator:latest -f Quivi.Migrator/Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/quivi.migrator:latest

      - name: Build Quivi.OAuth2
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/quivi.oauth2:latest -f Quivi.OAuth2/Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/quivi.oauth2:latest

      - name: Build Quivi.Backoffice.Api
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/quivi.backoffice.api:latest -f Quivi.Backoffice.Api/Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/quivi.backoffice.api:latest

      - name: Build Quivi.Hangfire
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/quivi.hangfire:latest -f Quivi.Hangfire/Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/quivi.hangfire:latest

      - name: Build Quivi.SignalR
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/quivi.signalr:latest -f Quivi.SignalR/Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/quivi.signalr:latest

      - name: Build Quivi.Pos.Api
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/quivi.pos.api:latest -f Quivi.Pos.Api/Dockerfile .
          docker push ${{ env.ACR_NAME }}.azurecr.io/quivi.pos.api:latest

      - name: Build quivi.backoffice.react.webapp
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/quivi.backoffice.react.webapp:latest -f quivi.backoffice.react.webapp/Dockerfile quivi.backoffice.react.webapp
          docker push ${{ env.ACR_NAME }}.azurecr.io/quivi.backoffice.react.webapp:latest

      - name: Build quivi.pos.react.app
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/quivi.pos.react.app:latest -f quivi.pos.react.app/Dockerfile quivi.pos.react.app
          docker push ${{ env.ACR_NAME }}.azurecr.io/quivi.pos.react.app:latest
          
      - name: Trigger Deploy Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"deploy_after_build"}'